#   docker compose build             
#   docker compose run --rm builder npm install
#   docker compose run --rm builder npm run build
#   docker compose run --rm builder npm run build:upload

services:
  builder:
    build: .
    volumes:
      - .:/app
    working_dir: /app
